export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem",
        }}
      >
        <p>Footer</p>
      </footer>
    </html>
  )
}
